### ISSUE TITLE
A transparent border appears at the bottom of the window

### ISSUE THREAD

**Issue by fansuregrin** [bahamondev/hide-titles#10]
As shown in the figure below, after the window is maximized and restored to its normal size, a transparent border appears at the bottom of the window.

![](https://github.com/fansuregrin/imgbed/blob/master/2021-06-16_22-33.png?raw=true)

**Comment by bahamondev** [comment]
distro & Plasma version?

**Comment by fansuregrin** [comment]
> distro & Plasma version? 

Sorry, I forgot to explain this information.
I use kde and archlinux. The kde version is 5.22.1.

**Comment by fansuregrin** [comment]
> > distro & Plasma version? 
> 
> Sorry, I forgot to explain this information.
> I use kde and archlinux. The kde version is 5.22.1. 

The situation where I have this problem is like this: I use the breeze window decoration, the window is set with a shadow, and I set the shortcut key to maximize.  When I opened your script, used the shortcut key to maximize and then used the shortcut key to restore the original window size, the problem in the picture appeared.  But when I close your script, repeat the above operation and it is normal.

**Comment by piotrintes** [comment]
That fixes that problem:

workspace.clientMaximizeSet.connect(function(client, horizontalMaximized, verticalMaximized) {
    if (config.allowed(client)) {
        if (horizontalMaximized && verticalMaximized) {
            csd.eval(client);
            client.noBorder = true;
        } else {
            client.noBorder = csd.isCsd(client);
            var geom = client.geometry;
            geom.x = geom.x + 1;
            client.geometry = geom;
            geom.x = geom.x - 1;
            client.geometry = geom;
        }
    }
});
